# Generated by Django 4.2.3 on 2023-11-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('Admin_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Role', models.CharField(choices=[('Superadmin', 'Superadmin'), ('Supervisor', 'Supervisor')], max_length=20)),
            ],
            options={
                'db_table': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('Candidate_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Candidate_Name', models.CharField(max_length=255)),
                ('Election_Year', models.IntegerField()),
                ('Candidate_Description', models.TextField()),
            ],
            options={
                'db_table': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='Constituencies',
            fields=[
                ('Constituency_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Constituency_Name', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Constituencies',
            },
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('Party_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Party_Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('Voter_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Registration_Date', models.DateTimeField()),
                ('Last_Login', models.DateTimeField(null=True)),
                ('Verified', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
            ],
            options={
                'db_table': 'Voters',
            },
        ),
        migrations.CreateModel(
            name='Voter_Details',
            fields=[
                ('Voter_Detail_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Date_of_Birth', models.DateField(null=True)),
                ('Address', models.TextField()),
                ('Contact_Number', models.CharField(max_length=15)),
                ('Voter_Card_Number', models.CharField(max_length=20)),
                ('Constituency_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voters.constituencies')),
                ('Voter_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voters')),
            ],
            options={
                'db_table': 'Voter_Details',
            },
        ),
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('Voted_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Vote_Date', models.DateTimeField()),
                ('Candidate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.candidates')),
                ('Voter_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voters')),
            ],
            options={
                'db_table': 'Voted',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('Supervisor_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.admins')),
                ('Constituency_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.constituencies')),
            ],
            options={
                'db_table': 'Supervisor',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('Log_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(max_length=255)),
                ('Action_Date', models.DateTimeField()),
                ('Action_Location', models.CharField(max_length=255)),
                ('Admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.admins')),
            ],
            options={
                'db_table': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('Election_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Election_Year', models.IntegerField()),
                ('Election_Schedule', models.DateTimeField()),
                ('Election_Status', models.CharField(max_length=20)),
                ('Constituency_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.constituencies')),
            ],
            options={
                'db_table': 'Election',
            },
        ),
        migrations.AddField(
            model_name='candidates',
            name='Constituency_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.constituencies'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='Party_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voters.parties'),
        ),
    ]
