# Generated by Django 4.2.7 on 2023-11-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constituencies',
            old_name='State',
            new_name='City',
        ),
    ]
