# Generated by Django 4.2.3 on 2023-11-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voters',
            name='Verified_By',
        ),
    ]
