# Generated by Django 4.2.3 on 2023-11-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_remove_voters_verified_by'),
        ('voters', '0002_rename_state_constituencies_city'),
    ]

    operations = [
    ]
