# Generated by Django 4.2.7 on 2023-11-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_merge_20231122_1140'),
        ('voters', '0003_merge_20231122_1317'),
    ]

    operations = [
    ]
